name: flutter_libserialport

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  libserialport: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterLibserialportPlugin
